services:
  esports:
    image: ${DOCKER_REGISTRY-}esports
    build:
      context: .
      dockerfile: esports/Dockerfile
    ports:
    - 8080:8080
    - 8081:8081
    depends_on:
      - esports-db

  esports-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: esports
      POSTGRES_PASSWORD: assword
    ports:
     - 5432:5432